development:
  database: billy_feedback_dev
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000

test:
  database: billy_feedback_test
  adapter: mysql2
  host: localhost
  pool: 5
  timeout: 5000

