development:
  sessions:
    default:
      database: bfb_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: bfb_production
      hosts:
        - localhost:27017